#!/bin/bash
# =============================================================================
# This script will format all the python source documents in the current and
# any lower directories.
#
# Usage:
#   format.sh
# =============================================================================
echo "-----------------------------------------------------------------------------"
echo Running black on all python source files,
echo "-----------------------------------------------------------------------------"
python -m black .
echo "-----------------------------------------------------------------------------"
echo Running isort on all python source files.
echo "-----------------------------------------------------------------------------"
python -m isort .
